### PR TITLE
Added continuous integration with Travis CI

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Checks if the build succeeds after each push.

Note: if you enjoy this, you'll have to change `richelbilderbeek` to `Ramblurr` and activate this repo on a to-be-made Travis CI account (free, easy and I am willing to help).

### CODE REVIEW

**Comment by Ramblurr** [comment]
I want to merge this pull request from quite a while ago:
https://github.com/Ramblurr/PietCreator/pull/4

Does your branch work with it?

**Comment by richelbilderbeek** [comment]
Nope, I though it would be better to add one step at a time. It does look like an interesting PR though and I can also fork his/her GitHub and add Travis support there :-)

**Comment by Ramblurr** [comment]
Can you please add a commit changing  `richelbilderbeek` to `Ramblurr` so I can merge it straight away?

**Comment by richelbilderbeek** [comment]
Sure, will do this now. You already have Travis CI activated?

**Comment by Ramblurr** [comment]
In the process of doing so :)

**Comment by richelbilderbeek** [comment]
Done.

**Comment by richelbilderbeek** [comment]
It works :-)

**Comment by Ramblurr** [comment]
And we're off! https://travis-ci.org/Ramblurr/PietCreator/builds/144109444

Thanks for the contribution!

**Comment by richelbilderbeek** [comment]
You're welcome. Let's this tool up-and-running again (I intend to fix #3 soon, after adding a Qt Creator .pro file that compiles the project, so you can expect some more PRs from me)

**Pull request merged**
